[package]
name = "turtle-van"
version = "1.0.0"
edition = "2024"

[dependencies]
serenity = { version="0.12.1", default-features = false, features = ["client", "gateway", "rustls_backend", "model", "voice", "cache", "standard_framework"] }
songbird = { version = "0.4.1", features = ["builtin-queue"] }
symphonia = { version = "0.5", features = [ "all-formats" ] }
dotenv = "0.15"
tokio = { version = "1", features = ["macros", "rt-multi-thread"] }
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["fmt"] }

reqwest = { version = "0.11", default-features = false, features = ["rustls-tls", "json", "socks"] }
poise = { version = "0.6.1-rc1", features = ["cache"] }
thiserror = "1.0.69"
