name: Deploy

on:
  push:
    tags:
      - 'prod-v[0-9]+.[0-9]+.[0-9]+'

jobs:
  deploy:
    runs-on: ubuntu-latest
    container: ghcr.io/railwayapp/cli:latest
    env:
      RAILWAY_TOKEN: ${{ secrets.RAILWAY_PROJECT_ID }}
      SVC_ID: ${{ secrets.RAILWAY_SERVICE_ID }}
    steps:
      - uses: actions/checkout@v4
      - run: railway up --service=${{ env.SVC_ID }} --environment=production
